name: CI Template

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Save Repository Code
        uses: actions/upload-artifact@v4
        with:
          name: repo-code
          path: .

  lint:
    name: Lint Code
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Code
        uses: actions/download-artifact@v4
        with:
          name: repo-code

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  test:
    name: Run Unit Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Code
        uses: actions/download-artifact@v4
        with:
          name: repo-code

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  style:
    name: Style Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Code
        uses: actions/download-artifact@v4
        with:
          name: repo-code

      - name: Install Dependencies
        run: npm ci

      - name: Check Styles
        run: npm run stylecheck

  codeql:
    name: Static Code Analysis with CodeQL
    needs: [lint, test, style]
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
