name: CI Template

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Save Repository Code
        uses: actions/upload-artifact@v4
        with:
          name: repo-code
          path: .

  lint:
    name: Lint Code
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Code
        uses: actions/download-artifact@v4
        with:
          name: repo-code

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  test:
    name: Run Unit Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Code
        uses: actions/download-artifact@v4
        with:
          name: repo-code

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  style:
    name: Style Check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Code
        uses: actions/download-artifact@v4
        with:
          name: repo-code

      - name: Install Dependencies
        run: npm ci

      - name: Check Styles
        run: npm run stylecheck
