name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml@main
    with:
      branch: ${{ github.ref }}
